# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Гривень', max_length=11)),
                ('par', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Змініть номінал на коректний'), django.core.validators.MaxValueValidator(2017, 'Змініть номінал на коректний')])),
                ('year_from', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1917, 'Змініть рік на коректний'), django.core.validators.MaxValueValidator(2017, 'Змініть рік на коректний')])),
                ('year_to', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1917, 'Змініть рік на коректний'), django.core.validators.MaxValueValidator(2017, 'Змініть рік на коректний')])),
                ('size', models.CharField(max_length=7)),
                ('sign', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='bons_images/%Y/%m/%d')),
            ],
        ),
    ]
