# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 14:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Гривня', 'Гривня'), ('Карбованець', 'Карбованець')], default='Гривня', max_length=11)),
                ('par', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Змініть номінал на коректний'), django.core.validators.MaxValueValidator(1000000, 'Змініть номінал на коректний')])),
                ('year', django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.contrib.postgres.validators.RangeMinValueValidator(1917), django.contrib.postgres.validators.RangeMaxValueValidator(2017)])),
                ('size', models.CharField(max_length=7)),
                ('sign', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='bons_images')),
            ],
        ),
    ]
