# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancnote',
            name='sign',
            field=models.TextField(max_length=100),
        ),
    ]
