# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170503_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancnote',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bancnote',
            name='sign',
            field=models.TextField(max_length=250),
        ),
    ]
