"""
Django settings for WCUB project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '57!+o08a2g$w5h&mvnpfya70&tw+@7o@7780=t&_5l8s##svo_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'catalogue.apps.CatalogueConfig',
    'widget_tweaks',
    'django_filters',
    'el_pagination',
    'captcha',
    'mathfilters',
    'disqus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'WCUB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalogue.context_processors.SubscribeFormGlobal',
            ],
        },
    },
]

WSGI_APPLICATION = 'WCUB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db.wcub',
        'USER': 'godis_michael',
        'PASSWORD': '211195',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

_ = lambda s: s

LANGUAGES = (
    ('uk', _('Ukrainian')),
    ('en', _('English')),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'catalogue/fixtures'),
)

EL_PAGINATION_LOADING = """<img src="/static/catalogue/img/loading.gif" style="width: 50px; height: 50px"/>"""
EL_PAGINATION_NEXT_LABEL = """<span>Попередні новини</span><i class="fa fa-angle-right" aria-hidden="true"></i>"""
EL_PAGINATION_PREVIOUS_LABEL = """<i class="fa fa-angle-left" aria-hidden="true"></i><span>Останні новини</span>"""

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django_mailgun.MailgunBackend'
# MAILGUN_ACCESS_KEY = 'key-0cfebad8a04a3747d4359f0c5832b4da'
# MAILGUN_SERVER_NAME = 'https://api.mailgun.net/v3/sandboxf0353b3b7145447facbf438f8474feb7.mailgun.org'
# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'postmaster@sandboxf0353b3b7145447facbf438f8474feb7.mailgun.org'
# EMAIL_HOST_PASSWORD = 'ba16d0aa70529184edf11fc11ef810ac'
# EMAIL_USE_TLS = True

GOOGLE_RECAPTCHA_SECRET_KEY = '6LefmiAUAAAAAC44FUrNQ-mmZbAm75DOqTzbQ4_j'
# RECAPTCHA_PUBLIC_KEY = '6LdIhiAUAAAAADlFnVeU_FkL2iKgbTtc_tFuohIi'
# RECAPTCHA_PRIVATE_KEY = '6LdIhiAUAAAAACtRx8TM6ulxd2TaSSyQ3Limp6Ic'
NOCAPTCHA = True

DISQUS_API_KEY = 'jMes5PPtmfLkto9EO5vVTjp53xZBuvfTnhVaW9uhflmWetI6Gcb4XqP1TCrfoHc3'
DISQUS_WEBSITE_SHORTNAME = 'wcub-1'

SITE_ID = 1
